"""
Bot configuration manager for Dad's MMO Lab.

Handles reading / writing bot settings (count, faction split, AH toggles)
and applying them to the active server's .env file so docker-compose picks
up the changes on the next  docker compose up.

Also provides helpers to query live bot status from the running database
(requires the server to be running with port 3306 exposed).
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path
from typing import Optional, Tuple

import config
import log_handler as log


# ─────────────────────────────────────────────────────────────────────────────
# .env writer
# ─────────────────────────────────────────────────────────────────────────────

def write_env_file(server_path: str | Path, cfg: dict) -> Tuple[bool, str]:
    """
    Write / overwrite the .env file next to docker-compose.yml.
    Reads bot settings from cfg (loaded via config.load()).
    Returns (success, message).
    """
    env_path = Path(server_path) / ".env"
    server_type = cfg.get("server_type", "base")

    lines = [
        "# Auto-generated by Dad's MMO Lab Launcher — do not edit manually.",
        "# Change Bot Settings in the launcher and click Apply to update.",
        "",
    ]

    if server_type == "npcbots":
        world_count    = int(cfg.get("npcbot_world_count",    40))
        faction_chance = int(cfg.get("npcbot_faction_chance", 500))
        lines += [
            "# ── NPCBots ──────────────────────────────────────────────────",
            f"NPCBOT_WORLD_COUNT={world_count}",
            f"NPCBOT_FACTION_CHANCE={faction_chance}",
            "",
        ]

    elif server_type == "playerbots":
        total    = int(cfg.get("playerbot_total_count",    50))
        alliance = int(cfg.get("playerbot_alliance_count", 25))
        horde    = int(cfg.get("playerbot_horde_count",    25))
        ah_buyer  = 1 if cfg.get("playerbot_ah_buyer",  True) else 0
        ah_seller = 1 if cfg.get("playerbot_ah_seller", True) else 0
        lines += [
            "# ── Playerbots ───────────────────────────────────────────────",
            f"PLAYERBOT_TOTAL_COUNT={total}",
            f"PLAYERBOT_ALLIANCE_COUNT={alliance}",
            f"PLAYERBOT_HORDE_COUNT={horde}",
            f"PLAYERBOT_AH_BUYER={ah_buyer}",
            f"PLAYERBOT_AH_SELLER={ah_seller}",
            "",
        ]

    else:
        # Base server — write an empty (comment-only) .env so compose is happy
        pass

    try:
        with open(env_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
        log.log(f"Bot config written → {env_path}", "INFO")
        return True, str(env_path)
    except OSError as exc:
        return False, str(exc)


# ─────────────────────────────────────────────────────────────────────────────
# Live bot status (requires running server)
# ─────────────────────────────────────────────────────────────────────────────

def _mysql_query(sql: str, db: str = "acore_characters") -> Optional[list]:
    """
    Run a SQL query via  docker exec ac_database  and return rows as a list
    of stripped strings.  Returns None on failure.
    """
    try:
        result = subprocess.run(
            [
                "docker", "exec", "ac_database",
                "mysql", "-uroot", "-pazeroth", db,
                "-e", sql, "--skip-column-names", "--batch",
            ],
            capture_output=True, text=True, timeout=10,
            encoding="utf-8", errors="replace",
        )
        if result.returncode != 0:
            return None
        rows = [line.strip() for line in result.stdout.splitlines() if line.strip()]
        return rows
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return None


def get_npcbot_status() -> dict:
    """
    Return a dict with wandering-bot counts from the live database.
    Keys: wandering_total, alliance, horde, error (str if unavailable).
    """
    rows = _mysql_query(
        "SELECT COUNT(*) FROM characters WHERE name LIKE 'RndBot%';",
        "acore_characters",
    )
    if rows is None:
        return {"error": "Database unreachable — is the server running?"}

    total = int(rows[0]) if rows else 0

    # Try faction breakdown (npcbots store faction in the characters.race column)
    # Alliance races: 1 Human, 3 Dwarf, 4 Night Elf, 7 Gnome, 11 Draenei, 22 Worgen
    alliance_races = "(1,3,4,7,11,22)"
    a_rows = _mysql_query(
        f"SELECT COUNT(*) FROM characters WHERE name LIKE 'RndBot%' AND race IN {alliance_races};",
        "acore_characters",
    )
    alliance = int(a_rows[0]) if a_rows else 0
    horde    = total - alliance

    return {"wandering_total": total, "alliance": alliance, "horde": horde}


def get_playerbot_status() -> dict:
    """
    Return a dict with playerbot counts from the live database.
    Keys: total, alliance, horde, ah_listings, error (str if unavailable).
    """
    rows = _mysql_query(
        "SELECT COUNT(*) FROM characters c "
        "JOIN acore_auth.account a ON c.account = a.id "
        "WHERE a.username LIKE 'rndbot%' OR a.username LIKE 'bot%';",
        "acore_characters",
    )
    if rows is None:
        return {"error": "Database unreachable — is the server running?"}

    total = int(rows[0]) if rows else 0

    # Alliance faction check
    alliance_races = "(1,3,4,7,11,22)"
    a_rows = _mysql_query(
        "SELECT COUNT(*) FROM characters c "
        f"JOIN acore_auth.account a ON c.account = a.id "
        f"WHERE (a.username LIKE 'rndbot%' OR a.username LIKE 'bot%') "
        f"AND c.race IN {alliance_races};",
        "acore_characters",
    )
    alliance = int(a_rows[0]) if a_rows else 0

    # AH bot listings
    ah_rows = _mysql_query(
        "SELECT COUNT(*) FROM auctionhouse WHERE itemowner = 0;",
        "acore_characters",
    )
    ah = int(ah_rows[0]) if ah_rows else 0

    return {
        "total":        total,
        "alliance":     alliance,
        "horde":        total - alliance,
        "ah_listings":  ah,
    }


def get_bot_status() -> dict:
    """
    Return a combined status dict for the currently configured server type.
    Always safe to call — returns an error message if the server isn't running.
    """
    cfg = config.load()
    server_type = cfg.get("server_type", "base")

    if server_type == "npcbots":
        return get_npcbot_status()
    elif server_type == "playerbots":
        return get_playerbot_status()
    else:
        return {"error": "Bot system not enabled for Base WoW server type."}
